# Generated by Django 4.0.1 on 2022-01-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_desc',
            field=models.TextField(max_length=1200),
        ),
        migrations.AlterField(
            model_name='post',
            name='desc',
            field=models.TextField(max_length=1200),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(max_length=600),
        ),
    ]
